# Kustomization file â€” apply all manifests at once:
#   kubectl apply -k k8s/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: credence

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: credence
